"""
This type stub file was generated by pyright.
"""

def download_url(url): # -> _UrlopenRet:
    ...

def download_url_to_data_uri(url, mime=...): # -> str:
    ...

def embed_css_resources(css): # -> str:
    '''Replace all URLs in the CSS string with downloaded data URIs.'''
    ...

def download_google_font_css(family, text=..., display=..., **kwargs): # -> str:
    '''Download SVG-embeddable CSS from Google fonts.

    Args:
        family: Name of font family or list of font families.
        text: The set of characters required from the font.  Only a font subset
            with these characters will be downloaded.
        display: The font-display CSS value.
        **kwargs: Other URL parameters sent to
            https://fonts.googleapis.com/css?...
    '''
    ...

