"""
This type stub file was generated by pyright.
"""

import dataclasses

class _Rasterizable:
    def rasterize(self, to_file=...): # -> Raster:
        ...
    


@dataclasses.dataclass
class JupyterSvgInline(_Rasterizable):
    '''Jupyter-displayable SVG displayed inline on the Jupyter web page.'''
    svg: str
    ...


@dataclasses.dataclass
class JupyterSvgImage(_Rasterizable):
    '''Jupyter-displayable SVG displayed within an img tag on the Jupyter web
    page.
    '''
    svg: str
    ...


@dataclasses.dataclass
class JupyterSvgFrame:
    '''Jupyter-displayable SVG displayed within an HTML iframe.'''
    svg: str
    width: float
    height: float
    mime: str = ...


