"""
This type stub file was generated by pyright.
"""

STRIP_CHARS = ...
def bytes_as_data_uri(data, strip_chars=..., mime=...): # -> str:
    '''Return a data URI with base64 encoding.'''
    ...

def svg_as_data_uri(txt, strip_chars=..., mime=...): # -> str:
    '''Return a data URI with base64 encoding, stripping unsafe chars for SVG.
    '''
    ...

def svg_as_utf8_data_uri(txt, unsafe_chars=..., strip_chars=..., mime=...): # -> str:
    '''Returns a data URI without base64 encoding.

    The characters '#&%' are always escaped.  '#' and '&' break parsing of
    the data URI.  If '%' is not escaped, plain text like '%50' will be
    incorrectly decoded to 'P'.  The characters in `strip_chars` cause the
    SVG not to render even if they are escaped.
    '''
    ...

