"""
This type stub file was generated by pyright.
"""

from .synced_animation import AnimatedAttributeTimeline, AnimationHelperData, SyncedAnimationConfig, animate_element_sequence, animate_text_sequence
from .playback_control_ui import draw_scrub

