"""
This type stub file was generated by pyright.
"""
from .synced_animation import SyncedAnimationConfig
from ..elements import Group


def draw_scrub(config: SyncedAnimationConfig, hidden=...) -> Group:
    ...
